// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW4LHbPmsVtNd3qI0ufll38aqt_oT7qHA',
    appId: '1:941945451696:web:3db3524bd33e41b941f775',
    messagingSenderId: '941945451696',
    projectId: 'banana-e83bf',
    authDomain: 'banana-e83bf.firebaseapp.com',
    storageBucket: 'banana-e83bf.firebasestorage.app',
    measurementId: 'G-14ZB3GM3Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfijPaNCEB9ddz4ZYNgvVDOIZewoOKkDE',
    appId: '1:941945451696:android:8ee92aa04166701d41f775',
    messagingSenderId: '941945451696',
    projectId: 'banana-e83bf',
    storageBucket: 'banana-e83bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMwjN62caHKsH91_1sMyLujetizRMzLLQ',
    appId: '1:941945451696:ios:008eae9e5254620941f775',
    messagingSenderId: '941945451696',
    projectId: 'banana-e83bf',
    storageBucket: 'banana-e83bf.firebasestorage.app',
    iosBundleId: 'com.example.banana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMwjN62caHKsH91_1sMyLujetizRMzLLQ',
    appId: '1:941945451696:ios:008eae9e5254620941f775',
    messagingSenderId: '941945451696',
    projectId: 'banana-e83bf',
    storageBucket: 'banana-e83bf.firebasestorage.app',
    iosBundleId: 'com.example.banana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW4LHbPmsVtNd3qI0ufll38aqt_oT7qHA',
    appId: '1:941945451696:web:6a747b0d7b07dac341f775',
    messagingSenderId: '941945451696',
    projectId: 'banana-e83bf',
    authDomain: 'banana-e83bf.firebaseapp.com',
    storageBucket: 'banana-e83bf.firebasestorage.app',
    measurementId: 'G-B0RWY1L9DJ',
  );

}